### ISSUE TITLE
Dúvida de como utilizar o código

### ISSUE THREAD

**Issue by DouglasFodi** [NatanBarbosa2/BlazeBot#2]
Bom dia, gostaria de saber como eu faço para rodar o código para deixar coletando e enviando as informações.

**Comment by NatanB4** [comment]
Boa noite Daafz, primeiro você precisa de um TOKEN de [bot do telegram](https://help.huggy.io/telegram-bot/como-configurar-o-telegram-boturl) logo depois executar o main.py em um editor de código(vscode, pycharm etc) é nescessario o python instalado além de também baixar as dependências.

Contudo não recomendo utilizar esse repositório para coisas que requerem mais atenção!  
Estou refazendo o BotBlaze pra ficar mais rápido, intuitivo e com uma interface para facilitar a vida de quem quiser utiliza-lo!
(Totalmente gratuito).

No mais só me chamar que eu irei lhe responder ;)

**Comment by DouglasFodi** [comment]
Eu acabei conseguindo fazer ele rodar, só que eu queria fazer umas alterações para em vez de ele fazer a analise por cor fazer o bot disparar uma mensagem a cada X minuto.

Agradeço a resposta e parabéns pelo trabalho já feito até o momento.

Fico no aguardo das atualizações ou do novo BotBlaze

**Comment by NatanB4** [comment]
> Eu acabei conseguindo fazer ele rodar, só que eu queria fazer umas alterações para em vez de ele fazer a analise por cor fazer o bot disparar uma mensagem a cada X minuto.
> 
> Agradeço a resposta e parabéns pelo trabalho já feito até o momento.
> 
> Fico no aguardo das atualizações ou do novo BotBlaze

Que bom! fico feliz. Poderia me explicar mais sobre essa funcionalidade de disparar uma nova mensagem?

**Comment by DouglasFodi** [comment]
Claro, o intuito dos bots da blaze é ele fazer a verificação das cores, por exemplo você aposta até G1 ou G2(GALE) no RED e dá BLACK ai vai pedir para a pessoa fazer o Gale 1, se girar e bater BLACK novamente G2, ai tem como fazer ele mandar a mensagem pelo Telegram, o que eu queria fazer era colocar para ele verificar as cores e colocar por exemplo para ele mandar o sinal para entrar no RED a cada 6 minutos, até estou tentando mas como não tenho muito conhecimento com python não estou conseguindo, se acaso precisar de ideias ou entender como funcionam algumas coisas estou aqui não tenho tanta experiência mas posso ajudar em algumas coisas.

**Comment by NatanB4** [comment]
Me parece ser bem tranquilo de adicionar isso!
Me chama no Discord: Natã#0711 ou no WhatsApp: 27999953836 pra gente conversar um pouco mais sobre suas ideias :)
